# Описание задачи
Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

1. перечень всех документов

documents = [
{‘type’: ‘passport’, ‘number’: ‘2207 876234’, ‘name’: ‘Василий Гупкин’},
{‘type’: ‘invoice’, ‘number’: ‘11-2’, ‘name’: ‘Геннадий Покемонов’},
{‘type’: ‘insurance’, ‘number’: ‘10006’, ‘name’: ‘Аристарх Павлов’}
]

2.перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)

directories = {
‘1’: [‘2207 876234’, ‘11-2’],
‘2’: [‘10006’],
‘3’: []
}

Общие требования к программе:

код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);
в коде отсутствуют глобальные переменные (за исключением documents и directories);
пользовательский ввод обрабатывается в цикле while до тех пор, пока пользователь явно не завершит программу (вводом команды “q”).

In [256]:
documents = [ {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'}, 
             {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'}, 
             {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'} ]

directories = { '1': ['2207 876234', '11-2'],
               '2': ['10006'], '3': [] }

# Далее под условием каждого задания приведён текст функции, реализующей данное задание.

# В конце, после всех заданий, приведён итоговый код программы, включающий все функции, работающий с вводом пользователя.

# Задание 1

## Пункт 1. Пользователь по команде “p” может узнать владельца документа по его номеру

Примеры работы:

Введите команду:
p

Введите номер документа:
10006

Результат:
Владелец документа: Аристарх Павлов

Введите команду:
p

Введите номер документа:
12345

Результат:
Документ не найден в базе

In [38]:
def user_search(doc_number):
    person = 'Документ не найден в базе'
    for doc in documents:
        if doc['number'] == doc_number:
            person = doc['name']
    return person

user_input = input('Введите команду ')

if user_input == 'p':
    doc_number = str(input('Введите номер документа '))
    print(f'Результат: {user_search(doc_number)}')

Введите команду p
Введите номер документа 10006
Результат: Аристарх Павлов


## Пункт 2. Пользователь по команде “s” может по номеру документа узнать на какой полке он хранится
Примеры работы:

Введите команду:
s

Введите номер документа:
10006

Результат:
Документ хранится на полке: 2

Введите команду:
p

Введите номер документа:
12345

Результат:
Документ не найден в базе

In [73]:
def shelf_search(doc_number):
    directory = 'Документ не найден в базе'
    for shelf in directories:
        if doc_number in directories[shelf]:
            directory = shelf
    return directory

user_input = input('Введите команду ')

if user_input == 'p':
    doc_number = str(input('Введите номер документа '))
    print(f'Результат: {user_search(doc_number)}')
elif user_input == 's':
    doc_number = str(input('Введите номер документа '))
    print(f'Результат: Документ хранится на полке: {shelf_search(doc_number)}')
else: print('Введена некорректная команда')

Введите команду s
Введите номер документа 2207 876234
Результат: Документ хранится на полке: 1


## Пункт 3. Пользователь по команде “l” может увидеть полную информацию по всем документам
Пример работы:

Введите команду:
l
Результат:

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [186]:
def print_all():
    complete_info = documents
    for doc in range(len(documents)):
        for shelf in directories:
            if documents[doc]['number'] in directories[shelf]:
                complete_info[doc]['полка хранения'] = shelf
    for line in range(len(complete_info)):
        print('№:', complete_info[line]['number'],
              ', тип:', complete_info[line]['type'],
              ', владелец', complete_info[line]['name'],
              ' , полка хранения:', complete_info[line]['полка хранения'])
print_all()

№: 2207 876234 , тип: passport , владелец Василий Гупкин  , полка хранения: 1
№: 11-2 , тип: invoice , владелец Геннадий Покемонов  , полка хранения: 1
№: 10006 , тип: insurance , владелец Аристарх Павлов  , полка хранения: 2


## Пункт 4. Пользователь по команде “as” может добавить новую полку
Примеры работы:

Введите команду:
as

Введите номер полки:
10

Результат:
Полка добавлена. Текущий перечень полок: 1, 2, 3, 10.

Введите команду:
as

Введите номер полки:
1

Результат:
Такая полка уже существует. Текущий перечень полок: 1, 2, 3.

In [130]:
def add_shelf():
    new_shelf = str(input('Введите номер полки: '))
    if new_shelf in directories.keys():
        print('Данная полка уже существует')
    else:
        directories[new_shelf] = []
        print(f'Полка добавлена. Текущий перечень полок: {list(directories.keys())}')

add_shelf()

Введите номер полки: 6
Полка добавлена. Текущий перечень полок: ['1', '2', '3', '4', '5', '6']


## Пункт 5. Пользователь по команде “ds” может удалить существующую полку из данных (только если она пустая)
Примеры работы:

Введите команду:
ds

Введите номер полки:
3
Результат:
Полка удалена. Текущий перечень полок: 1, 2.

Введите команду:
ds

Введите номер полки:
1
Результат:
На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.

Введите команду:
ds

Введите номер полки:
4
Результат:
Такой полки не существует. Текущий перечень полок: 1, 2, 3.

In [152]:
def delete_shelf():
    shelf_to_delete = str(input('Введите номер полки: '))
    if shelf_to_delete not in directories.keys():
        print(f'Данная полка не существует. Текущий перечень полок: {list(directories.keys())}')
    if shelf_to_delete in directories.keys() and bool(directories[shelf_to_delete]) == True:
        print(f'На полке есть документы, удалите их перед удалением полки. Текущий перечень полок: {list(directories.keys())}')
    if shelf_to_delete in directories.keys() and bool(directories[shelf_to_delete]) == False:
        del(directories[shelf_to_delete])
        print(f'Полка удалена. Текущий перечень полок: {list(directories.keys())}')

delete_shelf()

Введите номер полки: 3
Полка удалена. Текущий перечень полок: ['1', '2']


# Задание 2 (необязательное)
Вам необходимо дополнить программу из задания 1 более продвинутыми командами.

## Пункт 1. Пользователь по команде “ad” может добавить новый документ в данные
Примеры работы:

Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
3

Результат:

Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3

Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
4

Результат:

Такой полки не существует. Добавьте полку командой as.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [194]:
documents = [ {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'}, 
             {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'}, 
             {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'} ]

directories = { '1': ['2207 876234', '11-2'],
               '2': ['10006'], '3': [] }

def print_all():
    complete_info = documents
    for doc in range(len(documents)):
        for shelf in directories:
            if documents[doc]['number'] in directories[shelf]:
                complete_info[doc]['полка хранения'] = shelf
    for line in range(len(complete_info)):
        print('№:', complete_info[line]['number'],
              ', тип:', complete_info[line]['type'],
              ', владелец', complete_info[line]['name'],
              ' , полка хранения:', complete_info[line]['полка хранения'])

def add_document():
    number = str(input('Введите номер документа: '))
    typ = str(input('Введите тип документа: '))
    name = str(input('Введите владельца документа: '))
    shelf = str(input('Введите полку для хранения: '))
    if number not in directories.keys():
        print('')
        print('Такой полки не существует. Добавьте полку командой as. Текущий список документов: ')
        print_all()
    else:
        new_document = {'type': typ, 'number': number, 'name': name}
        documents.append(new_document)
        directories[shelf] = number
        print('')
        print('Документ добавлен. Текущий список документов: ')
        print_all()

add_document()

Введите номер документа: 1
Введите тип документа: 1
Введите владельца документа: 1
Введите полку для хранения: 3

Документ добавлен. Текущий список документов: 
№: 2207 876234 , тип: passport , владелец Василий Гупкин  , полка хранения: 1
№: 11-2 , тип: invoice , владелец Геннадий Покемонов  , полка хранения: 1
№: 10006 , тип: insurance , владелец Аристарх Павлов  , полка хранения: 2
№: 1 , тип: 1 , владелец 1  , полка хранения: 3


## Пункт 2. Пользователь по команде “d” может удалить документ из данных
Примеры работы:

Введите команду:
d

Введите номер документа:
10006

Результат:

Документ удален.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1

Введите команду:
d

Введите номер документа:
123456

Результат:

Документ не найден в базе.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [238]:
documents = [ {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'}, 
             {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'}, 
             {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'} ]

directories = { '1': ['2207 876234', '11-2'],
               '2': ['10006'], '3': [] }

def print_all():
    complete_info = documents
    for doc in range(len(documents)):
        for shelf in directories:
            if documents[doc]['number'] in directories[shelf]:
                complete_info[doc]['полка хранения'] = shelf
    for line in range(len(complete_info)):
        print('№:', complete_info[line]['number'],
              ', тип:', complete_info[line]['type'],
              ', владелец', complete_info[line]['name'],
              ' , полка хранения:', complete_info[line]['полка хранения'])

def delete_document():
    number = str(input('Введите номер документа: '))
    if number not in sum(directories.values(), []):
        print('')
        print('Документ не найден в базе. Текущий список документов: ')
        print_all()
    else:
        for doc in documents:
            if doc['number'] == number:
                string = doc
        documents.remove(string)
        for key in directories:
            if number in (directories[key]): k = key
        del(directories[k])
        print('')
        print('Документ удален. Текущий список документов: ')
        print_all()        

delete_document()

Введите номер документа: 5

Документ не найден в базе. Текущий список документов: 
№: 2207 876234 , тип: passport , владелец Василий Гупкин  , полка хранения: 1
№: 11-2 , тип: invoice , владелец Геннадий Покемонов  , полка хранения: 1
№: 10006 , тип: insurance , владелец Аристарх Павлов  , полка хранения: 2


## Пункт 3. Пользователь по команде “m” может переместить документ с полки на полку
Примеры работы:

Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
3

Результат:

Документ перемещен.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
10

Результат:
Такой полки не существует. Текущий перечень полок: 1, 2, 3.

Введите команду:
m

Введите номер документа:
42
Введите номер полки:
2

Результат:

Документ не найден в базе.
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [262]:
documents = [ {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'}, 
             {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'}, 
             {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'} ]

directories = { '1': ['2207 876234', '11-2'],
               '2': ['10006'], '3': [] }

def print_all():
    complete_info = documents
    for doc in range(len(documents)):
        for shelf in directories:
            if documents[doc]['number'] in directories[shelf]:
                complete_info[doc]['полка хранения'] = shelf
    for line in range(len(complete_info)):
        print('№:', complete_info[line]['number'],
              ', тип:', complete_info[line]['type'],
              ', владелец', complete_info[line]['name'],
              ' , полка хранения:', complete_info[line]['полка хранения'])

def move_document():
    number = str(input('Введите номер документа: '))
    shelf = str(input('Введите номер полки: '))
    if shelf not in directories.keys():
        print('')
        print(f'Данная полка не существует. Текущий перечень полок: {list(directories.keys())}')
    if number not in sum(directories.values(), []):
        print('')
        print('Документ не найден в базе. Текущий список документов: ')
        print_all()
    else:
        for shelf_to_remove in directories:
            if number in (directories[shelf_to_remove]):
                directories[shelf_to_remove].remove(number)
        directories[shelf] = number
        print('Документ перемещен. Текущий список документов: ')
        print_all()

move_document()

Введите номер документа: 11-2
Введите номер полки: 3
Документ перемещен. Текущий список документов: 
№: 2207 876234 , тип: passport , владелец Василий Гупкин  , полка хранения: 1
№: 11-2 , тип: invoice , владелец Геннадий Покемонов  , полка хранения: 3
№: 10006 , тип: insurance , владелец Аристарх Павлов  , полка хранения: 2


# Итоговая программа

In [265]:
documents = [ {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'}, 
             {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'}, 
             {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'} ]

directories = { '1': ['2207 876234', '11-2'],
               '2': ['10006'], '3': [] }

def user_search(doc_number):
    person = 'Документ не найден в базе'
    for doc in documents:
        if doc['number'] == doc_number:
            person = doc['name']
    return person

def shelf_search(doc_number):
    directory = 'Документ не найден в базе'
    for shelf in directories:
        if doc_number in directories[shelf]:
            directory = shelf
    return directory

def print_all():
    complete_info = documents
    for doc in range(len(documents)):
        for shelf in directories:
            if documents[doc]['number'] in directories[shelf]:
                complete_info[doc]['полка хранения'] = shelf
    for line in range(len(complete_info)):
        print('№:', complete_info[line]['number'],
              ', тип:', complete_info[line]['type'],
              ', владелец', complete_info[line]['name'],
              ' , полка хранения:', complete_info[line]['полка хранения'])

def add_shelf():
    new_shelf = str(input('Введите номер полки: '))
    if new_shelf in directories.keys():
        print('Данная полка уже существует')
    else:
        directories[new_shelf] = []
        print(f'Полка добавлена. Текущий перечень полок: {list(directories.keys())}')

def delete_shelf():
    shelf_to_delete = str(input('Введите номер полки: '))
    if shelf_to_delete not in directories.keys():
        print(f'Данная полка не существует. Текущий перечень полок: {list(directories.keys())}')
    if shelf_to_delete in directories.keys() and bool(directories[shelf_to_delete]) == True:
        print(f'На полке есть документы, удалите их перед удалением полки. Текущий перечень полок: {list(directories.keys())}')
    if shelf_to_delete in directories.keys() and bool(directories[shelf_to_delete]) == False:
        del(directories[shelf_to_delete])
        print(f'Полка удалена. Текущий перечень полок: {list(directories.keys())}')

def add_document():
    number = str(input('Введите номер документа: '))
    typ = str(input('Введите тип документа: '))
    name = str(input('Введите владельца документа: '))
    shelf = str(input('Введите полку для хранения: '))
    if number not in directories.keys():
        print('')
        print('Такой полки не существует. Добавьте полку командой as. Текущий список документов: ')
        print_all()
    else:
        new_document = {'type': typ, 'number': number, 'name': name}
        documents.append(new_document)
        directories[shelf] = number
        print('')
        print('Документ добавлен. Текущий список документов: ')
        print_all()

def delete_document():
    number = str(input('Введите номер документа: '))
    if number not in sum(directories.values(), []):
        print('')
        print('Документ не найден в базе. Текущий список документов: ')
        print_all()
    else:
        for doc in documents:
            if doc['number'] == number:
                string = doc
        documents.remove(string)
        for key in directories:
            if number in (directories[key]): k = key
        del(directories[k])
        print('')
        print('Документ удален. Текущий список документов: ')
        print_all()  
        
def move_document():
    number = str(input('Введите номер документа: '))
    shelf = str(input('Введите номер полки: '))
    if shelf not in directories.keys():
        print('')
        print(f'Данная полка не существует. Текущий перечень полок: {list(directories.keys())}')
    if number not in sum(directories.values(), []):
        print('')
        print('Документ не найден в базе. Текущий список документов: ')
        print_all()
    else:
        for shelf_to_remove in directories:
            if number in (directories[shelf_to_remove]):
                directories[shelf_to_remove].remove(number)
        directories[shelf] = number
        print('Документ перемещен. Текущий список документов: ')
        print_all()

while user_input != 'q':
    
    user_input = input('Введите команду ')

    if user_input == 'p':
        doc_number = str(input('Введите номер документа '))
        print(f'Результат: {user_search(doc_number)}')

    elif user_input == 's':
        doc_number = str(input('Введите номер документа '))
        print(f'Результат: Документ хранится на полке: {shelf_search(doc_number)}')

    elif user_input == 'l':
        print_all()

    elif user_input == 'as':
        add_shelf()

    elif user_input == 'ds':
        delete_shelf()

    elif user_input == 'ad':
        add_document()

    elif user_input == 'd':
        delete_document()

    elif user_input == 'm':
        move_document()

    elif user_input == 'q':
        break

    else: print('Введена некорректная команда')

Введите команду l
№: 2207 876234 , тип: passport , владелец Василий Гупкин  , полка хранения: 1
№: 11-2 , тип: invoice , владелец Геннадий Покемонов  , полка хранения: 1
№: 10006 , тип: insurance , владелец Аристарх Павлов  , полка хранения: 2
Введите команду q
